version: '3'

services:
  backend:
    build: ./
    container_name: dasafio-xp
    ports:
    - 3000:3000
    depends_on:
      - db
    restart: always
  db:
    container_name: Investimentos_DB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    restart: always